function [mod_psk, demod_psk] = build_mdm(waveform_params)
% Construction du modulateur
% -------------------------------------------------------------------------
mod_psk = comm.PSKModulator(...
    'ModulationOrder', waveform_params.mod.ModulationOrder, ...
    'PhaseOffset'    , waveform_params.mod.PhaseOffset, ...
    'SymbolMapping'  , waveform_params.mod.SymbolMapping,...
    'BitInput'       , waveform_params.mod.BitInput);
% -------------------------------------------------------------------------

% Construction du demodulateur
% -------------------------------------------------------------------------
demod_psk = comm.PSKDemodulator(...
    'ModulationOrder', waveform_params.demod.ModulationOrder, ...
    'PhaseOffset'    , waveform_params.demod.PhaseOffset, ...
    'SymbolMapping'  , waveform_params.demod.SymbolMapping,...
    'BitOutput'      , waveform_params.demod.BitOutput,...
    'DecisionMethod' , waveform_params.demod.DecisionMethod,...
    'Variance'       , waveform_params.demod.Variance);
% -------------------------------------------------------------------------
