function [tx_filter, rx_filter] = build_flt(waveform_params)
% Construction du filtre de mise en forme
% -------------------------------------------------------------------------
tx_filter   = comm.RaisedCosineTransmitFilter(...
    'FilterSpanInSymbols'   , waveform_params.txflt.FilterSpanInSymbols,...
    'RolloffFactor'         , waveform_params.txflt.RolloffFactor,...
    'OutputSamplesPerSymbol', waveform_params.txflt.OutputSamplesPerSymbol);
% -------------------------------------------------------------------------


% Construction du filtre adapte
% -------------------------------------------------------------------------
rx_filter   = comm.RaisedCosineReceiveFilter(...
    'FilterSpanInSymbols'  , waveform_params.rxflt.FilterSpanInSymbols,...
    'RolloffFactor'        , waveform_params.rxflt.RolloffFactor,...
    'InputSamplesPerSymbol', waveform_params.rxflt.InputSamplesPerSymbol,...
    'DecimationFactor'     , waveform_params.rxflt.DecimationFactor,...
    'DecimationOffset'     , waveform_params.rxflt.DecimationOffset);
end


